### ISSUE TITLE
Outbound proxy extention support 

### ISSUE THREAD

**Issue by shit-hub** [solo-io/wasm#115]
I apply a demo extension in istio environment.
When I send a request between pod, the extension will work in inbound proxy, but i want to it work as outbound proxy, because i want to use plugin to redirect request in outbound proxy. 
How can i achieve it.

**Comment by ilackarms** [comment]
hey @shit-hub thanks for commenting. to achieve this, we'd need to make the following (currently hard-coded) field configurable:

**Comment by Sodman** [comment]
Note: The file linked above has moved to https://github.com/solo-io/wasm/blob/ca6e5915fb1600a226e3cabcc60d22bd89661fb8/tools/wasme/cli/pkg/deploy/istio/istio_provider.go#L416

**Comment by fruffy** [comment]
What would need to be done to support this?
