### ISSUE TITLE
Support for Istio 1.7

### ISSUE THREAD

**Issue by Sodman** [solo-io/wasm#145]
Add support to wasme for Istio 1.7. We need to be able to create (init) and deploy filters that work with Istio 1.7.

There were no breaking envoy-wasm ABI changes between Istio 1.5 and Istio 1.6, so we should test a 1.6 image against Istio 1.7 to see if it's backwards compatible.

- If it is, we can simply add 1.7 to the same target as the existing 1.5 and 1.6. (See https://github.com/solo-io/wasme/pull/144).

- If it's not backwards compatible, we'll need to create a new ABI target for Istio 1.7.

**Comment by emayssat** [comment]
+1

**Comment by yuval-k** [comment]
asm script ABI was updated to support istio 1.7 in version 0.1.8

**Comment by JacksChoco** [comment]
+1

**Comment by xujinguang** [comment]
+1
