### ISSUE TITLE
Support other OCI than docker (like podman)

### ISSUE THREAD

**Issue by jotak** [solo-io/wasm#165]
Feature request: it would be nice to support other tool than docker for building images, such as podman. Is there any chance to have that?

Or perhaps, as an alternative, some documentation for how to build and push to webassemblyhub.io with manual steps, sort of bypassing what `wasme build` / `push` does?

**Comment by yuval-k** [comment]
yes, I agree; wasme push does not use docker, but rather the ORAS library;
wasme build does use docker to leverage build env containers; I think that make it configurable with podman shouldn't be too hard, podman should be compatible in our use case (no fancy networking done)

**Comment by Sodman** [comment]
Implemented by https://github.com/solo-io/wasm/pull/183
