### ISSUE TITLE
When installing wasme, unexpected errors occurred.

### ISSUE THREAD

**Issue by Xunzhuo** [solo-io/wasm#255]
**Describe the bug**

When installing wasme, unexpected errors occurred.

![image](https://user-images.githubusercontent.com/48784001/113651172-1715e780-96c4-11eb-90e7-c483b967709a.png)

**To Reproduce**
1. curl -sL https://run.solo.io/wasme/install | sh

**Expected behavior**

**Additional context**
Add any other context about the problem here, e.g.
- Gloo version
- Istio version

**Comment by Sodman** [comment]
Hi @Xunzhuo, what operating system are you using? Is your chipset amd64 or are you on ARM?

**Comment by Xunzhuo** [comment]
Operating system is centos and cpu based on x86 platform 😀

**Comment by Sodman** [comment]
Unfortunately right now the CLI is only supported on amd64 architecture on linux, macOS (darwin), and windows.

**Comment by Xunzhuo** [comment]
OK
