### ISSUE TITLE
how can i view the source code of a wasm plugin?

### ISSUE THREAD

**Issue by pyfdtic** [solo-io/wasm#263]
i find some awesome plugin in https://webassemblyhub.io/repositories/ , and i can also download the wasm format file, but it is a binary file.

is there a way i can view the source code of wasm plugin ? i want to add some feature by myself .

**Comment by Sodman** [comment]
Hi @pyfdtic, you are correct that the OCI images downloaded from the repository contain only the binary wasm file, and not the source. Filter authors can choose to list their open-source repository URL in the description of the wasm filter on webassemblyhub.io if they would like to, but it is not a requirement. If you are looking for the source code for a specific wasm filter, I would recommend reaching out to that filter's author directly.

**Comment by pyfdtic** [comment]
ok, thanks~ @Sodman
