### ISSUE TITLE
OCI Standard Image should support more than one layer

### ISSUE THREAD

**Issue by jcchavezs** [solo-io/wasm#292]
**Is your feature request related to a problem? Please describe.**
According to [the spec](https://github.com/solo-io/wasm/blob/master/spec/spec-compat.md#appendix-2-build-a-compat-image-with-docker-cli) OCI images should only contain one layer, however some use cases where you want to annotate the images with metadata aren't supported under this spec. For example [this issue](https://github.com/solo-io/wasm/issues/283) and the case where a docker image can't be annotated with labels because that generates more than one layer e.g.

```Dockerfile
FROM scratch

ARG OCI_SOURCE
ARG OCI_REVISION
LABEL org.opencontainers.image.title my-image
LABEL org.opencontainers.image.source $OCI_SOURCE
LABEL org.opencontainers.image.revision $OCI_REVISION

COPY ./build/my-wasm.wasm /plugin.wasm
```

**Describe the solution you'd like**
I think a good solution would be to make the convention that **the last layer** is going to be extracted instead of requiring to have **only one layer** (or two for artifacts)

**Describe alternatives you've considered**
Not annotating the images which is possible but labels help to search for sources of images.

cc @nacx @mathetake @anuraaga

**Comment by kdorosh** [comment]
this seems like a reasonable feature request / proposal to me. i'm not sure when the current team will have the bandwidth to take this on, but I'd be happy to work with you on this @jcchavezs if you want to make an open source contribution.

fyi @yuval-k

**Comment by jcchavezs** [comment]
Indeed I want to contribute to this! Next week will be.
