### ISSUE TITLE
cannot install with glooctl install gateway command

### ISSUE THREAD

**Issue by christian-posta** [solo-io/wasm#62]
from the docs, trying to run with this:

```
glooctl install gateway -n gloo-system --values <(echo '{"namespace":{"create":true},"crds":{"create":true},"global":{"wasm":{"enabled":true}}}')```

gives this consistently:

```
Gloo failed to install! Detailed logs available at /Users/ceposta/.gloo/debug.log.
Error: installing gloo in gateway mode: failed pre-install: warning: Hook pre-install gloo/templates/0-namespace.yaml failed: object is being deleted: namespaces "gloo-system" already exists
Usage:
  glooctl install gateway [flags]
  glooctl install gateway [command]

Available Commands:
  enterprise  install the Gloo Enterprise Gateway on Kubernetes

Flags:
  -h, --help   help for gateway

Global Flags:
  -c, --config string              set the path to the glooctl config file (default "<home_directory>/.gloo/glooctl-config.yaml")
      --consul-address string      address of the Consul server. Use with --use-consul (default "127.0.0.1:8500")
      --consul-datacenter string   Datacenter to use. If not provided, the default agent datacenter is used. Use with --use-consul
      --consul-root-key string     key prefix for for Consul key-value storage. (default "gloo")
      --consul-scheme string       URI scheme for the Consul server. Use with --use-consul (default "http")
      --consul-token string        Token is used to provide a per-request ACL token which overrides the agent's default token. Use with --use-consul
      --create-namespace           Create the namespace to install gloo into (default true)
  -d, --dry-run                    Dump the raw installation yaml instead of applying it to kubernetes
  -f, --file string                Install Gloo from this Helm chart archive file rather than from a release
  -i, --interactive                use interactive mode
      --kubeconfig string          kubeconfig to use, if not standard one
  -n, --namespace string           namespace to install gloo into (default "gloo-system")
      --release-name string        helm release name (default "gloo")
      --use-consul                 use Consul Key-Value storage as the backend for reading and writing config (VirtualServices, Upstreams, and Proxies)
      --values strings             List of files with value overrides for the Gloo Helm chart, (e.g. --values file1,file2 or --values file1 --values file2)
  -v, --verbose                    If true, output from kubectl commands will print to stdout/stderr
      --version string             version to install (e.g. 1.2.0, defaults to latest)
      --with-admin-console         install gloo and a read-only version of its admin console

Use "glooctl install gateway [command] --help" for more information about a command.
```

Also very odd here is there's nothing in the debug log.

**Comment by christian-posta** [comment]
I can workaround this with `--dry-run` and `kubectl apply -f -` but this needs to be fixed. Seems some bug in the helm installer within glooctl

**Comment by ilackarms** [comment]
@christian-posta can you open a corresponding issue on Gloo?

**Comment by mjaow** [comment]
yeah, I also met the issue today, this is the original command in offical docs
```
glooctl install gateway -n gloo-system --values <(echo '{"namespace":{"create":true},"crds":{"c
reate":true},"global":{"wasm":{"enabled":true}}}')
```

 I fix it by create namespace gloo-system by myself and install gloo without letting it create namespace
```
kubectl create ns gloo-system
glooctl install gateway -n gloo-system --values <(echo '{"namespace":{"create":false},"crds":{"c
reate":true},"global":{"wasm":{"enabled":true}}}')
```

**Comment by Sodman** [comment]
Hi @mjaow, the `glooctl` tool has been updated since this was created to automatically detect and create the namespace if it doesn't exist, so you can drop the namespace create part. Ie this should work on a fresh cluster:

```
glooctl install gateway -n gloo-system --values <(echo '{"crds":{"create":true},"global":{"wasm":{"enabled":true}}}') 
```

I've opened a PR to update the wasm docs here - https://github.com/solo-io/wasm/pull/224
