### ISSUE TITLE
wasme build cpp very very slowly

### ISSUE THREAD

**Issue by xujinguang** [solo-io/wasm#97]
base-info
```
型号名称：	MacBook Pro
型号标识符：	MacBookPro15,1
处理器名称：	6-Core Intel Core i7
处理器速度：	2.2 GHz
处理器数目：	1
核总数：	6
L2缓存（每个核）：	256 KB
L3缓存：	9 MB
超线程技术：	已启用
内存：	16 GB
```

```
$ wasme --version
wasme version 0.0.18
```

```
$ docker --version
Docker version 19.03.2, build 6a30dfc
```

the project use ` wasme init` to create, and change  nothing, build result:
```
Target //:filter.wasm up-to-date:
  bazel-bin/filter.wasm
INFO: Elapsed time: 594.232s, Critical Path: 67.32s
INFO: 287 processes: 287 processwrapper-sandbox.
INFO: Build completed successfully, 293 total actions
INFO: Build completed successfully, 293 total actions
INFO[0597] adding image to cache...                      filter file=/tmp/wasme439516905/filter.wasm tag="webassemblyhub.io/kowalski/modify-body:v0.1"
INFO[0597] tagged image                                  digest="sha256:390bf6d3428d3c4a025af1bb817957bed6fa926a3bf9a589aff8708f6171f6fa" image="webassemblyhub.io/kowalski/modify-body:v0.1"
```

**cost: 10m, my god!!!**  waste  time. so i try to optimize it

A)
1. add  docker volumn `/tmp/cache:/tmp/cache`
2. change bazel cmd: `bazel build --experimental_repository_cache=/tmp/cache ${TARGET}`
**No obvious change** —— fail

B)
1. add docker volumn `/tmp/cache:/root/.cache`
**cost time changed from 5 minutes to 20 minutes** —— fail

C)
1. remove docker param `--rm` 
2. try build once
3. use the container to commit a  new image
4. use the new image to build this project
**very good, it cost only tens of seconds** 
but this image just for this project, not suitable for other projects. because this bazel cache path (/root/.cache/...) has the project sign.

I personally think that this build speed greatly affects its use experience

**How to speed up the build?**

**Comment by yuval-k** [comment]
you might get better speed by using bazel directly; using docker makes everything easy to use, but is slower, especially when using docker for mac.
can you try using bazel command `bazel build //:filter.wasm` to see if there is improvement in speed?

**Comment by yuval-k** [comment]
also the initial build take longer as bazel downloads and configures emscripten for you.
we might be able to improve wasme to re-use the bazel cache - WDYT @ilackarms ?

**Comment by xujinguang** [comment]
> you might get better speed by using bazel directly; using docker makes everything easy to use, but is slower, especially when using docker for mac.
> can you try using bazel command `bazel build //:filter.wasm` to see if there is improvement in speed?

use  `bazel build //:filter.wasm`  local first build
```
Target //:filter.wasm up-to-date:
  bazel-bin/filter.wasm
INFO: Elapsed time: 459.281s, Critical Path: 86.77s
INFO: 34 processes: 34 darwin-sandbox.
INFO: Build completed successfully, 37 total actions
```

cost 8m,  The second build take about 2 m.

```
Target //:filter.wasm up-to-date:
  bazel-bin/filter.wasm
INFO: Elapsed time: 59.387s, Critical Path: 59.10s
INFO: 2 processes: 2 darwin-sandbox.
INFO: Build completed successfully, 3 total actions
```

**Comment by xujinguang** [comment]
> you might get better speed by using bazel directly; using docker makes everything easy to use, but is slower, especially when using docker for mac.
> can you try using bazel command `bazel build //:filter.wasm` to see if there is improvement in speed?

use bazel directly build `filter.wasm`,  just output one file, 
compare to building with docker, it seems to be missing 3 files：`descriptor.json    image_ref            runtime-config.json`（int dir `~/.wasme/store `）

I use cmd like this
```
$ wasme  push webassemblyhub.io/kowalski/modify-body:v0.3 bazel-bin/filter.wasm
INFO[0000] Pushing image webassemblyhub.io/kowalski/modify-body:v0.3 
INFO[0003] Pushed webassemblyhub.io/kowalski/modify-body:v0.3 
INFO[0003] Digest: sha256:19dc5615c3c77d427e56806d87a45a5a26086849ad4c21242ae15d00d85d3b50
```
but when i deploy it, i find filter.wasm sha256 not change

how to push it to webassemblyhub.io?

**Comment by Sodman** [comment]
Hi @xujinguang, a full tutorial for pushing wasm filter images can be found here - https://docs.solo.io/web-assembly-hub/latest/tutorial_code/push_tutorials/basic_push/

I'm closing this issue as stale, let me know if you're still experiencing issues and we can re-open if necessary.
