### ISSUE TITLE
recommend update wasme to support proxy_set_buffer_bytes

### ISSUE THREAD

**Issue by xujinguang** [solo-io/wasm#99]
```
e64efd960cd8e97287764b9bae39b3a0def95046
```
`envoy-wasm` commit support `proxy_set_buffer_bytes`, I recommend switching to this update.

url:
https://github.com/envoyproxy/envoy-wasm/commit/e64efd960cd8e97287764b9bae39b3a0def95046

**Comment by yuval-k** [comment]
do you know if this commit is included in istio? right now the spec is being formalized to have a version, but until that happens we have to track individual versions of envoy to see if they are included in istio as well..

**Comment by xujinguang** [comment]
> do you know if this commit is included in istio? right now the spec is being formalized to have a version, but until that happens we have to track individual versions of envoy to see if they are included in istio as well..

Thanks, I see. May be not included in istio. Let us check it.

**Comment by Sodman** [comment]
This is now available in the latest wasme releases, closing this Issue.
